# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Templakz

on:
    push:
        branches: [main]
    pull_request:
        branches: (*)

jobs:
    quality:
        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                node-version: [20.x]
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v4
            - name: Usar Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
            - run: npm ci

    publish:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        if: ${{github.ref == 'refs/heads/main'}}
        needs: [quality]
        steps:
            - uses: actions/checkout@v4
            - name: Usar Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
            - run: npm ci
            - run: npm run semantic-release
              env:
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
                  GH_TOKEN: ${{secrets.GH_TOKEN}}
